#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ENV_FILE=${FURA_ENV_FILE:-${SCRIPT_DIR}/.env}
OMP_ROOT="${SCRIPT_DIR}/vendor/oh-my-pi"

log() {
  printf '[setup] %s\n' "$*"
}

die() {
  printf '[setup] ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  local name=$1
  command -v "${name}" >/dev/null 2>&1 || die "Required command not found: ${name}"
}

env_file_declares() {
  local name=$1
  [[ -f "${ENV_FILE}" ]] && grep -Eq "^[[:space:]]*(export[[:space:]]+)?${name}=" "${ENV_FILE}"
}

persist_default() {
  local name=$1
  local fallback=$2
  local existing=${!name:-}
  local value=${existing:-${fallback}}

  if ! env_file_declares "${name}" || [[ -z "${existing}" ]]; then
    printf '%s=%q\n' "${name}" "${value}" >>"${ENV_FILE}"
  fi
  printf -v "${name}" '%s' "${value}"
  export "${name}"
}

require_command git
require_command cargo

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "${ENV_FILE}"
  set +a
else
  log "Creating ${ENV_FILE}"
  (umask 077; printf '# Generated by setup.sh; local secrets and machine paths only.\n' >"${ENV_FILE}")
fi

if [[ -n "${BUN_BIN:-}" ]]; then
  [[ -x "${BUN_BIN}" ]] || die "BUN_BIN is not executable: ${BUN_BIN}"
  resolved_bun=${BUN_BIN}
elif command -v bun >/dev/null 2>&1; then
  resolved_bun=$(command -v bun)
elif [[ -x "${HOME}/.bun/bin/bun" ]]; then
  resolved_bun="${HOME}/.bun/bin/bun"
else
  die "Bun is required. Install it from https://bun.sh and rerun ./setup.sh"
fi

token_default=${FURA_TOKEN:-}
if [[ -z "${token_default}" ]]; then
  token_default=$("${resolved_bun}" -e 'process.stdout.write(crypto.randomUUID().replaceAll("-", "") + crypto.randomUUID().replaceAll("-", ""));')
fi

persist_default FURA_DIR "${SCRIPT_DIR}"
persist_default BUN_BIN "${resolved_bun}"
persist_default FURA_TOKEN "${token_default}"
persist_default FURA_LOCAL_BIND "127.0.0.1:3737"
persist_default FURA_BRIDGE_DEBUG_FILE "${SCRIPT_DIR}/bridge-debug.jsonl"
persist_default FURA_EVENT_DEBUG_FILE "${SCRIPT_DIR}/fura-events.jsonl"

log "Initializing pinned OMP submodule"
git -C "${SCRIPT_DIR}" submodule update --init --recursive
[[ -d "${OMP_ROOT}/packages/coding-agent" ]] || die "OMP submodule is incomplete: ${OMP_ROOT}"

required_bun=$("${BUN_BIN}" -e 'const pkg = await Bun.file(Bun.argv[1]).json(); const raw = String(pkg.packageManager ?? pkg.engines?.bun ?? ""); const match = raw.match(/[0-9]+(?:\.[0-9]+){1,2}/); if (match) process.stdout.write(match[0]);' "${OMP_ROOT}/package.json")
current_bun=$("${BUN_BIN}" --version)
if [[ -n "${required_bun}" ]] && ! "${BUN_BIN}" -e 'process.exit(Bun.semver.order(Bun.argv[1], Bun.argv[2]) < 0 ? 1 : 0);' "${current_bun}" "${required_bun}"; then
  die "Bun ${current_bun} is too old; bundled OMP requires Bun >= ${required_bun}"
fi

log "Installing OMP dependencies"
(
  cd "${OMP_ROOT}"
  "${BUN_BIN}" install --frozen-lockfile
)

log "Building OMP native addon"
(
  cd "${OMP_ROOT}"
  env -u RUSTUP_TOOLCHAIN "${BUN_BIN}" run build:native
)

log "Checking OMP CLI"
(
  cd "${OMP_ROOT}/packages/coding-agent"
  PATH="$(dirname -- "${BUN_BIN}"):${PATH}" "${BUN_BIN}" src/cli.ts --version >/dev/null
)

log "Checking Fura/OMP RPC contract"
"${BUN_BIN}" "${SCRIPT_DIR}/scripts/check-omp-rpc-contract.ts"

log "Installing frontend dependencies"
if command -v npm >/dev/null 2>&1; then
  npm --prefix "${SCRIPT_DIR}/frontend" ci
else
  frontend_bun_lock="${SCRIPT_DIR}/frontend/bun.lock"
  had_frontend_bun_lock=0
  [[ -e "${frontend_bun_lock}" ]] && had_frontend_bun_lock=1
  "${BUN_BIN}" install --cwd "${SCRIPT_DIR}/frontend" --frozen-lockfile --no-save
  if (( had_frontend_bun_lock == 0 )); then
    rm -f -- "${frontend_bun_lock}"
  fi
fi

log "Building frontend"
if command -v npm >/dev/null 2>&1; then
  npm --prefix "${SCRIPT_DIR}/frontend" run build
else
  "${BUN_BIN}" run --cwd "${SCRIPT_DIR}/frontend" build
fi

log "Building Fura release binary"
cargo build --manifest-path "${SCRIPT_DIR}/Cargo.toml" --release --bin fura

cat <<EOF

Setup complete.

Run Fura with the bundled OMP fork:
  ./run-local-omp.sh

Run the bundled OMP directly:
  ./run-omp.sh

Open:
  http://${FURA_LOCAL_BIND}/

Token (also saved in .env):
  ${FURA_TOKEN}
EOF
